spring:
  application:
    name=market-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}db:3306/market
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
client:
  card-validator-service:
    url: https://run.mocky.io/v3/1164e4ea-6e5d-48c3-8c97-60efd9508789